[phases.setup]
nixPkgs = ['nodejs', 'python3', 'gcc']

[phases.install]
cmds = [
  'python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt',
  'npm install'
]

[start]
cmd = 'npm start'